ability to display private symbols differently
stevearc/aerial.nvim pull request #226
Opened 2023-03-11 13:42 UTC by emmanueltouzery

fixes #225

Implemented only the elixir private case. I thought just changing the icon wasn't enough, I had to make the text italic too. Maybe the icon should be the same color by default, this sets the icon for private symbols to NONE. I thought personally I needed all the help I could get to quickly spot the different public/private, so NONE suits me.

2023-03-11 13:45 UTC, emmanueltouzery commented
![image](https://user-images.githubusercontent.com/339433/224488142-286f7f73-c1e1-4e16-8f87-9ce694322abb.png)
![image](https://user-images.githubusercontent.com/339433/224488149-e593c385-bc00-4ce9-8df6-0a989f29f653.png)

screenshots on my setup on aerial's `elixir_test.exs`.

2023-03-13 03:48 UTC, stevearc requested changes
I think I would prefer adding another highlight group on top rather than creating another permutation for every SymbolKind. A function would have the hl group `AerialFunction`, a private function would have `AerialFunction` and then `AerialPrivate`. I think it provides better default behavior and scales better, but the downside is that if you want to have a different color for private functions vs private variables, it wouldn't support that. I think that's unlikely enough that the tradeoff is worth it. Thoughts?

In this world, I think we would still keep a separate group for the icons (e.g. `AerialFunctionIcon` + `AerialPrivateIcon`)

Could you also add `scope` to the [`aerial.Symbol` type definition](https://github.com/stevearc/aerial.nvim/blob/5b788392ec571621891e1b73887af5ac12056610/lua/aerial/data.lua#L10-L16)?

2023-03-13 03:48 UTC, stevearc commented on lua/aerial/highlight.lua
> +    vim.cmd(string.format("hi Aerial%sPrivate cterm=italic gui=italic", symbol_kind))
Would prefer for this to be the native lua function, and also to set the "default" highlight so it doesn't override settings that the user may already have in place
```lua
vim.api.nvim_set_hl(0, 'AerialPrivate', { default = true, italic = true})
```

2023-03-13 19:43 UTC, emmanueltouzery commented
One option requiring only a single highlight group would be to have everything exactly as it is today, plus a new option `specific_highlight_groups_for_scopes`.. It could be set to for instance `["Private"]`.
If you set it to `[]` you have the exact behavior of today.
If you set it to `["Private"]` then a private function would not anymore get the `AerialFunction` highlight group, but `AerialPrivate`. And so on.

It is less flexible than what you suggested though. But it might still be enough.

More flexible would be a map...
`specific_highlight_groups_for = {Function = ["Private"]}`.

And so on. Something like that could work with only single highlight groups. Just an idea.

2023-03-16 03:58 UTC, stevearc commented
Check out #228 for a proposal. This is similar to the last option you mention (single group for private function/variable/type/etc), but also exposes a `config.get_highlight` configuration option that would allow users to change the highlight group dynamically for any particular combination of SymbolKind + scope. What do you think?

2023-03-18 13:57 UTC, emmanueltouzery commented
superseded by #228 plus #229

2023-03-18 13:57 UTC, closed without merging