Add lualine component to render current symbol
stevearc/aerial.nvim pull request #26
Opened 2021-12-01 00:29 UTC by ikalnytskyi

Lualine is a widely used NeoVim statusline plugin. This patch adds a
lualine component that renders current symbol. It supports two rendering
modes:

1. When `hierarchy` is set to `true`, it renders the whole path to the
   current symbol including parent nodes.

2. Otherwise, it renders the current symbol only.

The component also respects `icons_enabled` option that can turn on/off
symbol icons rendering.

2021-12-01 00:31 UTC, ikalnytskyi commented
I'm also thinking about third rendering mode, something like:

```
{last_symbol_icon} {parent}.{parent}.{child}
```

:thinking:

2021-12-01 00:32 UTC, ikalnytskyi commented on lua/lualine/components/aerial.lua
> +  sep = " ⟩ ",
**n.b.** I can't call it `separator` since `separator` is reserved by `lualine`.

2021-12-01 00:32 UTC, ikalnytskyi commented on lua/lualine/components/aerial.lua
> +  hierarchy = true,
**Q:** What would be a better name?

2021-12-01 02:23 UTC, stevearc commented on lua/lualine/components/aerial.lua
> +  hierarchy = true,
I think hierarchy is good

2021-12-01 02:26 UTC, stevearc commented
LGTM! Could you add a comment at the top of the file showing how one would add it to the lualine config?

2021-12-01 22:54 UTC, ikalnytskyi commented
> Could you add a comment at the top of the file showing how one would add it to the lualine config?

Will do. I also want to try some other configuration first. I think I'll have some time to try it out tomorrow.

2021-12-03 12:37 UTC, ikalnytskyi commented
Hey @stevearc,

I just updated the patch. Can you please take a look once you have a moment? It may become a bit harder to read, yet I think it will cover most use cases out there.

2021-12-03 12:43 UTC, ikalnytskyi commented
I'm not happy about option names. If you have better ideas, please let me know.

2021-12-03 22:27 UTC, stevearc requested changes
Looks good! I think the option names are fine. Could you address the lint before merging?

2021-12-04 12:13 UTC, ikalnytskyi commented
I think I fixed them.

2021-12-04 18:23 UTC, stevearc commented
Looks good, thanks for the PR!

2021-12-04 18:23 UTC, merged