Feature: Set jumplist before jumping
stevearc/aerial.nvim pull request #305
Opened 2023-10-13 05:21 UTC by wbthomason

Closes #266. We may also want to add a configuration parameter if users should be able to disable/enable this behavior, but I think it's a reasonable enough default that it may be OK to wait for complaints before adding this.

I have not tested this extensively with weird window options/layouts, etc., but it has worked for my basic use case.

2023-10-13 08:28 UTC, max397574 commented on lua/aerial/navigation.lua
> +    vim.api.nvim_buf_set_mark(vim.api.nvim_get_current_buf(), [[']], old_cursor[1], old_cursor[2])
```suggestion
    vim.api.nvim_buf_set_mark(vim.api.nvim_get_current_buf(), [[']], unpack(old_cursor))
```

2023-10-13 16:58 UTC, wbthomason commented on lua/aerial/navigation.lua
> +    vim.api.nvim_buf_set_mark(vim.api.nvim_get_current_buf(), [[']], old_cursor[1], old_cursor[2])
@max397574 Good suggestion, thanks!

2023-10-15 01:47 UTC, stevearc requested changes
Added some notes about edge cases.

I will note that I did a couple of tests myself just playing around with setting the `'` mark, and had trouble getting it to behave correctly. I didn't look into it too much, but it's entirely possible that setting the marks this way via the API behaves differently than when you do it via the `m'` normal mode command.

2023-10-15 01:47 UTC, stevearc commented on lua/aerial/navigation.lua
> +    vim.api.nvim_buf_set_mark(vim.api.nvim_get_current_buf(), [[']], unpack(old_cursor))
I apologize for the terrible naming, this API needs some refactoring. The "jump" parameter doesn't mean what you think it means. When it's true, it means that we will focus the source window as part of this navigation action. So when you're just navigating around within the same buffer using `:AerialNext/Prev`, this value will be false.

Another thing to note: we're jumping to a location in `winid`, but `winid` is not necessarily the active window right here. You'll probably need to use `nvim_win_get_buf()` for the buffer, and you might need to do a `nvim_win_call` as well to make sure the mark is set in the appropriate window. If you want to test it, I would expect this to come up if your cursor is in the aerial window when you run `:AerialNext/Prev`.

2024-05-22 21:22 UTC, yalikebaz commented
Just wanted to nudge this a little, would be super helpful to have jumplist integrated here 🙏 
if not... I've customized my telescope picker to somewhat look like `AerialToggle`, and this works with the jumplist by default:

```
:lua require('telescope').extensions.aerial.aerial(require('telescope.themes').get_dropdown({layout_strategy='vertical', layout_config={vertical={anchor='E', width=0.2, height=0.9}}, previewer=false, sorting_strategy='ascending', results_title=false, prompt_title=false, border=false}))<CR>
```

2024-11-03 20:28 UTC, stevearc commented
Implemented by #424

2024-11-03 20:28 UTC, closed without merging