Allow setting [privacy] scope from queries
stevearc/aerial.nvim pull request #317
Opened 2023-10-17 16:18 UTC by Slotos

This has direct impact on highlighting. If scope is set and set to anything but "public", highlighter will use a separate highlight for the corresponding entry. This was previously used by Elixir extension by manually processing nodes.

Elixir extension processing is removed, its queries updated, and fixed to consider not just `defp`, but also `defguardp` and `defmacrop` as private.

Ruby queries are updated to deal with both predicate and statement versions of scope setting. The query is kinda brittle still, as anything unexpected in between methods definitions will break it. "Not" match would solve the problem, but treesitter doesn't provide one. A custom predicate might be a way to go, but better is the enemy of good, so I'm stopping here.

2023-10-18 00:39 UTC, stevearc requested changes
This looks good, apart from the note about the elixir changes.

You mentioned wanting to have a negated match; Neovim does have some built in predicates for that (see `:help lua-treesitter-not-predicate`). You might be able to use `#not-any-of?`

2023-10-18 00:39 UTC, stevearc commented on queries/elixir/aerial.scm
> +
I think adding the scope with `#set!` is a good additional capability, but for the elixir case I feel like we should use the previous extension-based logic. It's so much cleaner to have a single if-statement to set the scope than to duplicate this entire query

2023-10-19 18:07 UTC, Slotos commented
I ended up adding quite a few interleaving scope switches to ruby test case, since I'm relying on behaviours that I haven't found any documentation for.
Namely, the scoping query relies on specific nodes `(identifier)` winning against a catchall `(_)` one in an alternation query.

I have a few ideas about streamlining the whole proces by processing `@scope` node capture, but for now they are just that - ideas.

2023-10-20 04:34 UTC, stevearc commented
Cool, this LGTM!

2023-10-20 04:35 UTC, merged