Process @scope captures and add basic query documentation
stevearc/aerial.nvim pull request #318
Opened 2023-10-24 20:44 UTC by Slotos

This lets us avoid complex querying when extracting scope.
As long as the capture includes a scoping node in a `@scope` capture, its text will be extracted and used as a scope value.
If "public" is named differently in some language, `#set @scope "text" "public"` will do the trick for a cost of maybe an additional query.

Ruby queries got condenced and cleaned up, which was the primary motivation for this PR.

PS: I'd split implementation and documentation into separate commits for ease of cherry-picking.

2023-11-01 00:10 UTC, stevearc requested changes
Scope capture change makes sense. Just a couple of nits about the documentation

2023-11-01 00:28 UTC, stevearc commented on README.md
> +- `@selection` - position to jump to when using Aerial for navigation, only used if `treesitter.experimental_selection_range` is enabled, falls back to `@name` and `@type`
I've also just shipped the selection range option, so there is no flag and this is always enabled

2023-11-02 15:53 UTC, Slotos commented on README.md
> +
Makes sense.
I'll move these descriptions to `@note` comments of specific extensions, to aid future contributions.

2023-11-04 19:13 UTC, stevearc commented on README.md
> +
SGTM

2023-11-10 15:39 UTC, stevearc commented
Thanks for the PR!

2023-11-10 15:39 UTC, merged