feat(backend): add asciidoc
stevearc/aerial.nvim pull request #348
Opened 2024-02-28 04:36 UTC by cathaysia

2024-03-01 04:55 UTC, stevearc requested changes
Can you add tests? Add an asciidoc file to [tests/](https://github.com/stevearc/aerial.nvim/tree/master/tests) and write a test that calls `util.test_file_symbols`. Here's where we're doing it for the markdown backend:

https://github.com/stevearc/aerial.nvim/blob/d21482d3be3228dde594aba31106db428292742c/tests/treesitter_spec.lua#L38-L42

It's embedded in the treesitter test because we use the same source file. You can put this in a standalone test file. Once you do that, run `./run_tests.sh --update` to generate a symbols snapshot file.

2024-03-01 09:17 UTC, cathaysia commented
I add a test for asciidoc, but it failed in my computer. Could you give me some suggest?

2024-03-01 17:14 UTC, stevearc requested changes
I've fixed the test for you, but left a comment about code block parsing.

(note: the objdump test is still failing, but that's unrelated to this PR)

2024-03-02 04:33 UTC, cathaysia commented on lua/aerial/backends/asciidoc.lua
> +      inside_code_block = not inside_code_block
I add codes check title inside block and test it manually, but symbol/asciidoc_backend.json maybe need update.

2024-03-02 04:48 UTC, cathaysia commented on lua/aerial/backends/asciidoc.lua
> +      inside_code_block = not inside_code_block
I updated this json file. :)

2024-03-02 23:23 UTC, merged

2024-03-02 23:23 UTC, stevearc commented
Thanks for the PR!