Add basic support for navigating zig files.
stevearc/aerial.nvim pull request #359
Opened 2024-04-05 19:37 UTC by g-cassie

This is very basic level support but it's enough for me personally to get value out of this plugin while doing zig development.

I tried to have it differentiate between methods and functions but it would end up dropping structs which contain methods.

2024-04-05 21:32 UTC, g-cassie commented
I've found a couple rough edges on this. Will continue to work on ironing it out but let me know if you are okay with merging it eventually.

2024-04-13 22:15 UTC, stevearc commented
I'd definitely be up for merging! Just add a test file to https://github.com/stevearc/aerial.nvim/tree/master/tests/treesitter with at least one instance of each symbol type that is supported and run `make update_snapshots` to generate the symbol snapshot.

2024-04-13 22:17 UTC, stevearc requested changes
Sending back to you until tests are added

2024-04-16 15:49 UTC, g-cassie commented
Thanks - test added.  Pretty nice testing setup!

2024-04-16 20:27 UTC, stevearc commented
Awesome, looks great! The test failure looks unrelated; I just need to adapt to something that changed upstream. Thanks for the contribution!

2024-04-16 20:27 UTC, merged